package net.minecraft;

public class amk {

	public static final Item a;
	public static final Item b;
	public static final Item c;
	public static final Item d;
	public static final Item e;
	public static final ajz f;
	public static final Item g;
	public static final Item h;
	public static final Item i;
	public static final Item j;
	public static final Item k;
	public static final Item l;
	public static final Item m;
	public static final Item n;
	public static final Item o;
	public static final Item p;
	public static final Item q;
	public static final Item r;
	public static final Item s;
	public static final Item t;
	public static final Item u;
	public static final Item v;
	public static final Item w;
	public static final Item x;
	public static final Item y;
	public static final Item z;
	public static final Item A;
	public static final Item B;
	public static final Item C;
	public static final Item D;
	public static final Item E;
	public static final Item F;
	public static final Item G;
	public static final Item H;
	public static final Item I;
	public static final Item J;
	public static final Item K;
	public static final Item L;
	public static final Item M;
	public static final Item N;
	public static final Item O;
	public static final Item P;
	public static final ajn Q;
	public static final ajn R;
	public static final ajn S;
	public static final ajn T;
	public static final ajn U;
	public static final ajn V;
	public static final ajn W;
	public static final ajn X;
	public static final ajn Y;
	public static final ajn Z;
	public static final ajn aa;
	public static final ajn ab;
	public static final ajn ac;
	public static final ajn ad;
	public static final ajn ae;
	public static final ajn af;
	public static final ajn ag;
	public static final ajn ah;
	public static final ajn ai;
	public static final ajn aj;
	public static final Item ak;
	public static final Item al;
	public static final Item am;
	public static final Item an;
	public static final Item ao;
	public static final Item ap;
	public static final Item aq;
	public static final Item ar;
	public static final Item as;
	public static final Item at;
	public static final Item au;
	public static final Item av;
	public static final Item aw;
	public static final Item ax;
	public static final Item ay;
	public static final Item az;
	public static final Item aA;
	public static final Item aB;
	public static final Item aC;
	public static final Item aD;
	public static final Item aE;
	public static final Item aF;
	public static final Item aG;
	public static final Item aH;
	public static final Item aI;
	public static final Item aJ;
	public static final Item aK;
	public static final Item aL;
	public static final Item aM;
	public static final Item aN;
	public static final Item aO;
	public static final Item aP;
	public static final Item aQ;
	public static final alj aR;
	public static final Item aS;
	public static final Item aT;
	public static final Item aU;
	public static final Item aV;
	public static final Item aW;
	public static final Item aX;
	public static final Item aY;
	public static final Item aZ;
	public static final Item ba;
	public static final Item bb;
	public static final Item bc;
	public static final amn bd;
	public static final and be;
	public static final Item bf;
	public static final Item bg;
	public static final Item bh;
	public static final Item bi;
	public static final Item bj;
	public static final Item bk;
	public static final Item bl;
	public static final Item bm;
	public static final Item bn;
	public static final Item bo;
	public static final Item bp;
	public static final Item bq;
	public static final Item br;
	public static final Item bs;
	public static final Item bt;
	public static final Item bu;
	public static final Item bv;
	public static final Item bw;
	public static final Item bx;
	public static final Item by;
	public static final amw bz;
	public static final Item bA;
	public static final Item bB;
	public static final Item bC;
	public static final Item bD;
	public static final Item bE;
	public static final Item bF;
	public static final Item bG;
	public static final Item bH;
	public static final Item bI;
	public static final Item bJ;
	public static final Item bK;
	public static final Item bL;
	public static final Item bM;
	public static final Item bN;
	public static final Item bO;
	public static final Item bP;
	public static final Item bQ;
	public static final Item bR;
	public static final Item bS;
	public static final Item bT;
	public static final Item bU;
	public static final akz bV;
	public static final Item bW;
	public static final Item bX;
	public static final Item bY;
	public static final Item bZ;
	public static final Item ca;
	public static final Item cb;
	public static final Item cc;
	public static final ala cd;
	public static final Item ce;
	public static final Item cf;
	public static final Item cg;
	public static final Item ch;
	public static final Item ci;
	public static final ajq cj;
	public static final Item ck;
	public static final Item cl;
	public static final Item cm;
	public static final Item cn;
	public static final Item co;
	public static final Item cp;
	public static final Item cq;
	public static final Item cr;
	public static final Item cs;
	public static final Item ct;
	public static final Item cu;
	public static final Item cv;
	public static final Item cw;
	public static final Item cx;
	public static final Item cy;
	public static final Item cz;
	public static final Item cA;
	public static final Item cB;
	public static final Item cC;
	public static final Item cD;
	public static final Item cE;

	private static Item a(String var0) {
		return (Item) Item.REGISTRY.a(new oa(var0));
	}

	static {
		if (!od.a()) {
			throw new RuntimeException("Accessed Items before Bootstrap!");
		} else {
			a = a("iron_shovel");
			b = a("iron_pickaxe");
			c = a("iron_axe");
			d = a("flint_and_steel");
			e = a("apple");
			f = (ajz) a("bow");
			g = a("arrow");
			h = a("coal");
			i = a("diamond");
			j = a("iron_ingot");
			k = a("gold_ingot");
			l = a("iron_sword");
			m = a("wooden_sword");
			n = a("wooden_shovel");
			o = a("wooden_pickaxe");
			p = a("wooden_axe");
			q = a("stone_sword");
			r = a("stone_shovel");
			s = a("stone_pickaxe");
			t = a("stone_axe");
			u = a("diamond_sword");
			v = a("diamond_shovel");
			w = a("diamond_pickaxe");
			x = a("diamond_axe");
			y = a("stick");
			z = a("bowl");
			A = a("mushroom_stew");
			B = a("golden_sword");
			C = a("golden_shovel");
			D = a("golden_pickaxe");
			E = a("golden_axe");
			F = a("string");
			G = a("feather");
			H = a("gunpowder");
			I = a("wooden_hoe");
			J = a("stone_hoe");
			K = a("iron_hoe");
			L = a("diamond_hoe");
			M = a("golden_hoe");
			N = a("wheat_seeds");
			O = a("wheat");
			P = a("bread");
			Q = (ajn) a("leather_helmet");
			R = (ajn) a("leather_chestplate");
			S = (ajn) a("leather_leggings");
			T = (ajn) a("leather_boots");
			U = (ajn) a("chainmail_helmet");
			V = (ajn) a("chainmail_chestplate");
			W = (ajn) a("chainmail_leggings");
			X = (ajn) a("chainmail_boots");
			Y = (ajn) a("iron_helmet");
			Z = (ajn) a("iron_chestplate");
			aa = (ajn) a("iron_leggings");
			ab = (ajn) a("iron_boots");
			ac = (ajn) a("diamond_helmet");
			ad = (ajn) a("diamond_chestplate");
			ae = (ajn) a("diamond_leggings");
			af = (ajn) a("diamond_boots");
			ag = (ajn) a("golden_helmet");
			ah = (ajn) a("golden_chestplate");
			ai = (ajn) a("golden_leggings");
			aj = (ajn) a("golden_boots");
			ak = a("flint");
			al = a("porkchop");
			am = a("cooked_porkchop");
			an = a("painting");
			ao = a("golden_apple");
			ap = a("sign");
			aq = a("wooden_door");
			ar = a("spruce_door");
			as = a("birch_door");
			at = a("jungle_door");
			au = a("acacia_door");
			av = a("dark_oak_door");
			aw = a("bucket");
			ax = a("water_bucket");
			ay = a("lava_bucket");
			az = a("minecart");
			aA = a("saddle");
			aB = a("iron_door");
			aC = a("redstone");
			aD = a("snowball");
			aE = a("boat");
			aF = a("leather");
			aG = a("milk_bucket");
			aH = a("brick");
			aI = a("clay_ball");
			aJ = a("reeds");
			aK = a("paper");
			aL = a("book");
			aM = a("slime_ball");
			aN = a("chest_minecart");
			aO = a("furnace_minecart");
			aP = a("egg");
			aQ = a("compass");
			aR = (alj) a("fishing_rod");
			aS = a("clock");
			aT = a("glowstone_dust");
			aU = a("fish");
			aV = a("cooked_fish");
			aW = a("dye");
			aX = a("bone");
			aY = a("sugar");
			aZ = a("cake");
			ba = a("bed");
			bb = a("repeater");
			bc = a("cookie");
			bd = (amn) a("filled_map");
			be = (and) a("shears");
			bf = a("melon");
			bg = a("pumpkin_seeds");
			bh = a("melon_seeds");
			bi = a("beef");
			bj = a("cooked_beef");
			bk = a("chicken");
			bl = a("cooked_chicken");
			bm = a("mutton");
			bn = a("cooked_mutton");
			bo = a("rabbit");
			bp = a("cooked_rabbit");
			bq = a("rabbit_stew");
			br = a("rabbit_foot");
			bs = a("rabbit_hide");
			bt = a("rotten_flesh");
			bu = a("ender_pearl");
			bv = a("blaze_rod");
			bw = a("ghast_tear");
			bx = a("gold_nugget");
			by = a("nether_wart");
			bz = (amw) a("potion");
			bA = a("glass_bottle");
			bB = a("spider_eye");
			bC = a("fermented_spider_eye");
			bD = a("blaze_powder");
			bE = a("magma_cream");
			bF = a("brewing_stand");
			bG = a("cauldron");
			bH = a("ender_eye");
			bI = a("speckled_melon");
			bJ = a("spawn_egg");
			bK = a("experience_bottle");
			bL = a("fire_charge");
			bM = a("writable_book");
			bN = a("written_book");
			bO = a("emerald");
			bP = a("item_frame");
			bQ = a("flower_pot");
			bR = a("carrot");
			bS = a("potato");
			bT = a("baked_potato");
			bU = a("poisonous_potato");
			bV = (akz) a("map");
			bW = a("golden_carrot");
			bX = a("skull");
			bY = a("carrot_on_a_stick");
			bZ = a("nether_star");
			ca = a("pumpkin_pie");
			cb = a("fireworks");
			cc = a("firework_charge");
			cd = (ala) a("enchanted_book");
			ce = a("comparator");
			cf = a("netherbrick");
			cg = a("quartz");
			ch = a("tnt_minecart");
			ci = a("hopper_minecart");
			cj = (ajq) a("armor_stand");
			ck = a("iron_horse_armor");
			cl = a("golden_horse_armor");
			cm = a("diamond_horse_armor");
			cn = a("lead");
			co = a("name_tag");
			cp = a("command_block_minecart");
			cq = a("record_13");
			cr = a("record_cat");
			cs = a("record_blocks");
			ct = a("record_chirp");
			cu = a("record_far");
			cv = a("record_mall");
			cw = a("record_mellohi");
			cx = a("record_stal");
			cy = a("record_strad");
			cz = a("record_ward");
			cA = a("record_11");
			cB = a("record_wait");
			cC = a("prismarine_shard");
			cD = a("prismarine_crystals");
			cE = a("banner");
		}
	}
}
