package net.minecraft;

public class Blocks {

	public static final Block AIR;
	public static final Block STONE;
	public static final BlockGrass GRASS;
	public static final Block DIRT;
	public static final Block COBBLESTONE;
	public static final Block PLANKS;
	public static final Block SAPLING;
	public static final Block BEDROCK;
	public static final BlockFlowing FLOWING_WATER;
	public static final BlockStationary WATER;
	public static final BlockFlowing FLOWING_LAVA;
	public static final BlockStationary LAVA;
	public static final BlockSand SAND;
	public static final Block GRAVEL;
	public static final Block GOLD_ORE;
	public static final Block IRON_ORE;
	public static final Block COAL_ORE;
	public static final Block LOG;
	public static final Block LOG2;
	public static final BlockLeaves LEAVES;
	public static final BlockLeaves LEAVES2;
	public static final Block SPONGE;
	public static final Block GLASS;
	public static final Block LAPIS_ORE;
	public static final Block LAPIS_BLOCK;
	public static final Block DISPENSER;
	public static final Block SANDSTONE;
	public static final Block NOTEBLOCK;
	public static final Block BED;
	public static final Block GOLDEN_RAIL;
	public static final Block DETECTOR_RAIL;
	public static final BlockPiston STICKY_PISTON;
	public static final Block WEB;
	public static final BlockLongGrass TALLGRASS;
	public static final BlockDeadBush DEADBUSH;
	public static final BlockPiston PISTON;
	public static final BlockPistonExtension PISTON_HEAD;
	public static final Block WOOL;
	public static final BlockPistonMoving PISTON_EXTENSION;
	public static final avy YELLOW_FLOWER;
	public static final avy RED_FLOWER;
	public static final auc BRWON_MUSHROOM;
	public static final auc RED_MUSHROOM;
	public static final Block GOLD_BLOCK;
	public static final Block IRON_BLOCK;
	public static final BlockStepAbstract DOUBLE_STONE_SLAB;
	public static final BlockStepAbstract STONE_SLAB;
	public static final Block BRICK_BLOCK;
	public static final Block TNT;
	public static final Block BOOKSHELF;
	public static final Block MOSSY_COBBLESTONE;
	public static final Block OBSIDIAN;
	public static final Block TORCH;
	public static final BlockFire FIRE;
	public static final Block MOB_SPAWNER;
	public static final Block OAK_STAIRS;
	public static final BlockChest CHEST;
	public static final BlockRedstoneWire REDSTONE_WIRE;
	public static final Block DIAMOND_ORE;
	public static final Block DIAMOND_BLOCK;
	public static final Block CRAFTING_TABLE;
	public static final Block WHEAT;
	public static final Block FARMLAND;
	public static final Block FURNACE;
	public static final Block LIT_FURNACE;
	public static final Block STANDING_SIGN;
	public static final Block WOODEN_DOOR;
	public static final Block SPRUCE_DOOR;
	public static final Block BIRCH_DOOR;
	public static final Block JUNGLE_DOOR;
	public static final Block ACACIA_DOOR;
	public static final Block DARK_OAK_DOOR;
	public static final Block LADDER;
	public static final Block RAIL;
	public static final Block STONE_STAIRS;
	public static final Block WALL_SIGN;
	public static final Block LEVER;
	public static final Block STONE_PRESSURE_PLATE;
	public static final Block IRON_DOOR;
	public static final Block WOODEN_PRESSURE_PLATE;
	public static final Block REDSTONE_ORE;
	public static final Block LIT_REDSTONE_ORE;
	public static final Block UNLIT_REDSTONE_TORCH;
	public static final Block REDSTONE_TORCH;
	public static final Block STONE_BUTTON;
	public static final Block SNOW_LAYER;
	public static final Block ICE;
	public static final Block SNOW;
	public static final BlockCactus CACTUS;
	public static final Block CLAY;
	public static final BlockReed REEDS;
	public static final Block JUKEBOX;
	public static final Block FENCE;
	public static final Block SPRUCE_FENCE;
	public static final Block BIRCH_FENCE;
	public static final Block JUNGLE_FENCE;
	public static final Block DARK_OAK_FENCE;
	public static final Block ACACIA_FENCE;
	public static final Block PUMPKIN;
	public static final Block NETHERRACK;
	public static final Block SOUL_SAND;
	public static final Block GLOWSTONE;
	public static final BlockPortal PORTAL;
	public static final Block LIT_PUMPKIN;
	public static final Block CAKE;
	public static final BlockRepeater UNPOWERED_REPEATER;
	public static final BlockRepeater POWERED_REPEATER;
	public static final Block TRAPDOOR;
	public static final Block MONSTER_EGG;
	public static final Block STONEBRICK;
	public static final Block BROWN_MUSHROOM_BLOCK;
	public static final Block RED_MUSHROOM_BLOCK;
	public static final Block IRON_BARS;
	public static final Block GLASS_PANE;
	public static final Block MELON_BLOCK;
	public static final Block PUMPKIN_STEM;
	public static final Block MELON_STEM;
	public static final Block VINE;
	public static final Block FENCE_GATE;
	public static final Block SPRUCE_FENCE_GATE;
	public static final Block BIRCH_FENCE_GATE;
	public static final Block JUNGLE_FENCE_GATE;
	public static final Block DARK_OAK_FENCE_GATE;
	public static final Block ACACIA_FENCE_GATE;
	public static final Block BRICK_STAIRS;
	public static final Block STONE_BROCK_STAIRS;
	public static final BlockMycel MYCELIUM;
	public static final Block WATERLILY;
	public static final Block NETHER_BRICK;
	public static final Block NETHER_BRICK_FENCE;
	public static final Block NETHER_BRICK_STAIRS;
	public static final Block NETHER_WART;
	public static final Block ENCHANTING_TABLE;
	public static final Block BREWING_STAND;
	public static final BlockCauldron CAULDRON;
	public static final Block END_PORTAL;
	public static final Block END_PORTAL_FRAME;
	public static final Block END_STONE;
	public static final Block DRAGON_EGG;
	public static final Block REDSTONE_LAMP;
	public static final Block LIT_REDSTONE_LAMP;
	public static final BlockStepAbstract DOUBLE_WOODEN_SLAB;
	public static final BlockStepAbstract WOODEN_SLAB;
	public static final Block COCOA;
	public static final Block SANDSTONE_STAIRS;
	public static final Block EMERALD_ORE;
	public static final Block ENDER_CHEST;
	public static final BlockTripwireHook TRIPWIRE_HOOK;
	public static final Block TRIPWIRE;
	public static final Block EMERALD_BLOCK;
	public static final Block SPRUCE_STAIRS;
	public static final Block BIRCH_STAIRS;
	public static final Block JUNGLE_STAIRS;
	public static final Block COMMAND_BLOCK;
	public static final BlockBeacon BEACON;
	public static final Block COBBLESTONE_WALL;
	public static final Block FLOWER_POT;
	public static final Block CARROTS;
	public static final Block POTATOES;
	public static final Block WOODEN_BUTTON;
	public static final BlockSkull SKULL;
	public static final Block ANVIL;
	public static final Block TRAPPED_CHEST;
	public static final Block LIGHT_WEIGHTED_PRESSURE_PLATE;
	public static final Block HEAVY_WEIGHTED_PRESSURE_PLATE;
	public static final BlockRedstoneComparator UNPOWERED_COMPARATOR;
	public static final BlockRedstoneComparator POWERED_COMPARATOR;
	public static final BlockDaylightDetector DAYLIGHT_DETECTOR;
	public static final BlockDaylightDetector DAYLIGHT_DETECTOR_INVERTED;
	public static final Block REDSTONE_BLOCK;
	public static final Block QUARTZ_ORE;
	public static final BlockHopper HOPPER;
	public static final Block QUARTZ_BLOCK;
	public static final Block QUARTZ_STAIRS;
	public static final Block ACTIVATOR_RAIL;
	public static final Block DROPPER;
	public static final Block STAINDED_HARDENED_CLAY;
	public static final Block BARRIER;
	public static final Block IRON_TRAPDOOR;
	public static final Block HAY_BLOCK;
	public static final Block CARPET;
	public static final Block HARDENED_CLAY;
	public static final Block COAL_BLOCK;
	public static final Block PACKED_ICE;
	public static final Block ACACIA_STAIRS;
	public static final Block DARK_OAK_STAIRS;
	public static final Block SLIME;
	public static final BlockTallPlant DOUBLE_PLANT;
	public static final BlockStainedGlass STAINED_GLASS;
	public static final BlockStainedGlassPane STAINED_GLASS_PANE;
	public static final Block PRISMARINE;
	public static final Block SEA_LANTERN;
	public static final Block STANDING_BANNER;
	public static final Block WALL_BANNER;
	public static final Block RED_SANDSTONE;
	public static final Block RED_SANDSTONE_STAIRS;
	public static final BlockStepAbstract DOUBLE_STONE_SLAB2;
	public static final BlockStepAbstract STONE_SLAB2;

	private static Block getBlock(String name) {
		return (Block) Block.BLOCKREGISTRY.getByName(new RegistryObjectName(name));
	}

	static {
		if (!Bootstrap.isReady()) {
			throw new RuntimeException("Accessed Blocks before Bootstrap!");
		} else {
			AIR = getBlock("air");
			STONE = getBlock("stone");
			GRASS = (BlockGrass) getBlock("grass");
			DIRT = getBlock("dirt");
			COBBLESTONE = getBlock("cobblestone");
			PLANKS = getBlock("planks");
			SAPLING = getBlock("sapling");
			BEDROCK = getBlock("bedrock");
			FLOWING_WATER = (BlockFlowing) getBlock("flowing_water");
			WATER = (BlockStationary) getBlock("water");
			FLOWING_LAVA = (BlockFlowing) getBlock("flowing_lava");
			LAVA = (BlockStationary) getBlock("lava");
			SAND = (BlockSand) getBlock("sand");
			GRAVEL = getBlock("gravel");
			GOLD_ORE = getBlock("gold_ore");
			IRON_ORE = getBlock("iron_ore");
			COAL_ORE = getBlock("coal_ore");
			LOG = getBlock("log");
			LOG2 = getBlock("log2");
			LEAVES = (BlockLeaves) getBlock("leaves");
			LEAVES2 = (BlockLeaves) getBlock("leaves2");
			SPONGE = getBlock("sponge");
			GLASS = getBlock("glass");
			LAPIS_ORE = getBlock("lapis_ore");
			LAPIS_BLOCK = getBlock("lapis_block");
			DISPENSER = getBlock("dispenser");
			SANDSTONE = getBlock("sandstone");
			NOTEBLOCK = getBlock("noteblock");
			BED = getBlock("bed");
			GOLDEN_RAIL = getBlock("golden_rail");
			DETECTOR_RAIL = getBlock("detector_rail");
			STICKY_PISTON = (BlockPiston) getBlock("sticky_piston");
			WEB = getBlock("web");
			TALLGRASS = (BlockLongGrass) getBlock("tallgrass");
			DEADBUSH = (BlockDeadBush) getBlock("deadbush");
			PISTON = (BlockPiston) getBlock("piston");
			PISTON_HEAD = (BlockPistonExtension) getBlock("piston_head");
			WOOL = getBlock("wool");
			PISTON_EXTENSION = (BlockPistonMoving) getBlock("piston_extension");
			YELLOW_FLOWER = (avy) getBlock("yellow_flower");
			RED_FLOWER = (avy) getBlock("red_flower");
			BRWON_MUSHROOM = (auc) getBlock("brown_mushroom");
			RED_MUSHROOM = (auc) getBlock("red_mushroom");
			GOLD_BLOCK = getBlock("gold_block");
			IRON_BLOCK = getBlock("iron_block");
			DOUBLE_STONE_SLAB = (BlockStepAbstract) getBlock("double_stone_slab");
			STONE_SLAB = (BlockStepAbstract) getBlock("stone_slab");
			BRICK_BLOCK = getBlock("brick_block");
			TNT = getBlock("tnt");
			BOOKSHELF = getBlock("bookshelf");
			MOSSY_COBBLESTONE = getBlock("mossy_cobblestone");
			OBSIDIAN = getBlock("obsidian");
			TORCH = getBlock("torch");
			FIRE = (BlockFire) getBlock("fire");
			MOB_SPAWNER = getBlock("mob_spawner");
			OAK_STAIRS = getBlock("oak_stairs");
			CHEST = (BlockChest) getBlock("chest");
			REDSTONE_WIRE = (BlockRedstoneWire) getBlock("redstone_wire");
			DIAMOND_ORE = getBlock("diamond_ore");
			DIAMOND_BLOCK = getBlock("diamond_block");
			CRAFTING_TABLE = getBlock("crafting_table");
			WHEAT = getBlock("wheat");
			FARMLAND = getBlock("farmland");
			FURNACE = getBlock("furnace");
			LIT_FURNACE = getBlock("lit_furnace");
			STANDING_SIGN = getBlock("standing_sign");
			WOODEN_DOOR = getBlock("wooden_door");
			SPRUCE_DOOR = getBlock("spruce_door");
			BIRCH_DOOR = getBlock("birch_door");
			JUNGLE_DOOR = getBlock("jungle_door");
			ACACIA_DOOR = getBlock("acacia_door");
			DARK_OAK_DOOR = getBlock("dark_oak_door");
			LADDER = getBlock("ladder");
			RAIL = getBlock("rail");
			STONE_STAIRS = getBlock("stone_stairs");
			WALL_SIGN = getBlock("wall_sign");
			LEVER = getBlock("lever");
			STONE_PRESSURE_PLATE = getBlock("stone_pressure_plate");
			IRON_DOOR = getBlock("iron_door");
			WOODEN_PRESSURE_PLATE = getBlock("wooden_pressure_plate");
			REDSTONE_ORE = getBlock("redstone_ore");
			LIT_REDSTONE_ORE = getBlock("lit_redstone_ore");
			UNLIT_REDSTONE_TORCH = getBlock("unlit_redstone_torch");
			REDSTONE_TORCH = getBlock("redstone_torch");
			STONE_BUTTON = getBlock("stone_button");
			SNOW_LAYER = getBlock("snow_layer");
			ICE = getBlock("ice");
			SNOW = getBlock("snow");
			CACTUS = (BlockCactus) getBlock("cactus");
			CLAY = getBlock("clay");
			REEDS = (BlockReed) getBlock("reeds");
			JUKEBOX = getBlock("jukebox");
			FENCE = getBlock("fence");
			SPRUCE_FENCE = getBlock("spruce_fence");
			BIRCH_FENCE = getBlock("birch_fence");
			JUNGLE_FENCE = getBlock("jungle_fence");
			DARK_OAK_FENCE = getBlock("dark_oak_fence");
			ACACIA_FENCE = getBlock("acacia_fence");
			PUMPKIN = getBlock("pumpkin");
			NETHERRACK = getBlock("netherrack");
			SOUL_SAND = getBlock("soul_sand");
			GLOWSTONE = getBlock("glowstone");
			PORTAL = (BlockPortal) getBlock("portal");
			LIT_PUMPKIN = getBlock("lit_pumpkin");
			CAKE = getBlock("cake");
			UNPOWERED_REPEATER = (BlockRepeater) getBlock("unpowered_repeater");
			POWERED_REPEATER = (BlockRepeater) getBlock("powered_repeater");
			TRAPDOOR = getBlock("trapdoor");
			MONSTER_EGG = getBlock("monster_egg");
			STONEBRICK = getBlock("stonebrick");
			BROWN_MUSHROOM_BLOCK = getBlock("brown_mushroom_block");
			RED_MUSHROOM_BLOCK = getBlock("red_mushroom_block");
			IRON_BARS = getBlock("iron_bars");
			GLASS_PANE = getBlock("glass_pane");
			MELON_BLOCK = getBlock("melon_block");
			PUMPKIN_STEM = getBlock("pumpkin_stem");
			MELON_STEM = getBlock("melon_stem");
			VINE = getBlock("vine");
			FENCE_GATE = getBlock("fence_gate");
			SPRUCE_FENCE_GATE = getBlock("spruce_fence_gate");
			BIRCH_FENCE_GATE = getBlock("birch_fence_gate");
			JUNGLE_FENCE_GATE = getBlock("jungle_fence_gate");
			DARK_OAK_FENCE_GATE = getBlock("dark_oak_fence_gate");
			ACACIA_FENCE_GATE = getBlock("acacia_fence_gate");
			BRICK_STAIRS = getBlock("brick_stairs");
			STONE_BROCK_STAIRS = getBlock("stone_brick_stairs");
			MYCELIUM = (BlockMycel) getBlock("mycelium");
			WATERLILY = getBlock("waterlily");
			NETHER_BRICK = getBlock("nether_brick");
			NETHER_BRICK_FENCE = getBlock("nether_brick_fence");
			NETHER_BRICK_STAIRS = getBlock("nether_brick_stairs");
			NETHER_WART = getBlock("nether_wart");
			ENCHANTING_TABLE = getBlock("enchanting_table");
			BREWING_STAND = getBlock("brewing_stand");
			CAULDRON = (BlockCauldron) getBlock("cauldron");
			END_PORTAL = getBlock("end_portal");
			END_PORTAL_FRAME = getBlock("end_portal_frame");
			END_STONE = getBlock("end_stone");
			DRAGON_EGG = getBlock("dragon_egg");
			REDSTONE_LAMP = getBlock("redstone_lamp");
			LIT_REDSTONE_LAMP = getBlock("lit_redstone_lamp");
			DOUBLE_WOODEN_SLAB = (BlockStepAbstract) getBlock("double_wooden_slab");
			WOODEN_SLAB = (BlockStepAbstract) getBlock("wooden_slab");
			COCOA = getBlock("cocoa");
			SANDSTONE_STAIRS = getBlock("sandstone_stairs");
			EMERALD_ORE = getBlock("emerald_ore");
			ENDER_CHEST = getBlock("ender_chest");
			TRIPWIRE_HOOK = (BlockTripwireHook) getBlock("tripwire_hook");
			TRIPWIRE = getBlock("tripwire");
			EMERALD_BLOCK = getBlock("emerald_block");
			SPRUCE_STAIRS = getBlock("spruce_stairs");
			BIRCH_STAIRS = getBlock("birch_stairs");
			JUNGLE_STAIRS = getBlock("jungle_stairs");
			COMMAND_BLOCK = getBlock("command_block");
			BEACON = (BlockBeacon) getBlock("beacon");
			COBBLESTONE_WALL = getBlock("cobblestone_wall");
			FLOWER_POT = getBlock("flower_pot");
			CARROTS = getBlock("carrots");
			POTATOES = getBlock("potatoes");
			WOODEN_BUTTON = getBlock("wooden_button");
			SKULL = (BlockSkull) getBlock("skull");
			ANVIL = getBlock("anvil");
			TRAPPED_CHEST = getBlock("trapped_chest");
			LIGHT_WEIGHTED_PRESSURE_PLATE = getBlock("light_weighted_pressure_plate");
			HEAVY_WEIGHTED_PRESSURE_PLATE = getBlock("heavy_weighted_pressure_plate");
			UNPOWERED_COMPARATOR = (BlockRedstoneComparator) getBlock("unpowered_comparator");
			POWERED_COMPARATOR = (BlockRedstoneComparator) getBlock("powered_comparator");
			DAYLIGHT_DETECTOR = (BlockDaylightDetector) getBlock("daylight_detector");
			DAYLIGHT_DETECTOR_INVERTED = (BlockDaylightDetector) getBlock("daylight_detector_inverted");
			REDSTONE_BLOCK = getBlock("redstone_block");
			QUARTZ_ORE = getBlock("quartz_ore");
			HOPPER = (BlockHopper) getBlock("hopper");
			QUARTZ_BLOCK = getBlock("quartz_block");
			QUARTZ_STAIRS = getBlock("quartz_stairs");
			ACTIVATOR_RAIL = getBlock("activator_rail");
			DROPPER = getBlock("dropper");
			STAINDED_HARDENED_CLAY = getBlock("stained_hardened_clay");
			BARRIER = getBlock("barrier");
			IRON_TRAPDOOR = getBlock("iron_trapdoor");
			HAY_BLOCK = getBlock("hay_block");
			CARPET = getBlock("carpet");
			HARDENED_CLAY = getBlock("hardened_clay");
			COAL_BLOCK = getBlock("coal_block");
			PACKED_ICE = getBlock("packed_ice");
			ACACIA_STAIRS = getBlock("acacia_stairs");
			DARK_OAK_STAIRS = getBlock("dark_oak_stairs");
			SLIME = getBlock("slime");
			DOUBLE_PLANT = (BlockTallPlant) getBlock("double_plant");
			STAINED_GLASS = (BlockStainedGlass) getBlock("stained_glass");
			STAINED_GLASS_PANE = (BlockStainedGlassPane) getBlock("stained_glass_pane");
			PRISMARINE = getBlock("prismarine");
			SEA_LANTERN = getBlock("sea_lantern");
			STANDING_BANNER = getBlock("standing_banner");
			WALL_BANNER = getBlock("wall_banner");
			RED_SANDSTONE = getBlock("red_sandstone");
			RED_SANDSTONE_STAIRS = getBlock("red_sandstone_stairs");
			DOUBLE_STONE_SLAB2 = (BlockStepAbstract) getBlock("double_stone_slab2");
			STONE_SLAB2 = (BlockStepAbstract) getBlock("stone_slab2");
		}
	}

}
