package net.minecraft;

public class Blocks {

	public static final Block AIR;
	public static final Block STONE;
	public static final BlockGrass GRASS;
	public static final Block DIRT;
	public static final Block COBBLESTONE;
	public static final Block PLANKS;
	public static final Block SAPLING;
	public static final Block BEDROCK;
	public static final BlockFlowing FLOWING_WATER;
	public static final BlockStationary WATER;
	public static final BlockFlowing FLOWING_LAVA;
	public static final BlockStationary LAVA;
	public static final BlockSand SAND;
	public static final Block GRAVEL;
	public static final Block GOLD_ORE;
	public static final Block IRON_ORE;
	public static final Block COAL_ORE;
	public static final Block LOG;
	public static final Block LOG2;
	public static final BlockLeaves LEAVES;
	public static final BlockLeaves LEAVES2;
	public static final Block SPONGE;
	public static final Block GLASS;
	public static final Block LAPIS_ORE;
	public static final Block LAPIS_BLOCK;
	public static final Block DISPENSER;
	public static final Block SANDSTONE;
	public static final Block NOTEBLOCK;
	public static final Block BED;
	public static final Block GOLDEN_RAIL;
	public static final Block DETECTOR_RAIL;
	public static final BlockPiston STICKY_PISTON;
	public static final Block WEB;
	public static final BlockLongGrass TALLGRASS;
	public static final BlockDeadBush DEADBUSH;
	public static final BlockPiston PISTON;
	public static final BlockPistonExtension PISTON_HEAD;
	public static final Block WOOL;
	public static final BlockPistonMoving PISTON_EXTENSION;
	public static final avy YELLOW_FLOWER;
	public static final avy RED_FLOWER;
	public static final auc BRWON_MUSHROOM;
	public static final auc RED_MUSHROOM;
	public static final Block GOLD_BLOCK;
	public static final Block IRON_BLOCK;
	public static final BlockStepAbstract DOUBLE_STONE_SLAB;
	public static final BlockStepAbstract STONE_SLAB;
	public static final Block BRICK_BLOCK;
	public static final Block TNT;
	public static final Block BOOKSHELF;
	public static final Block MOSSY_COBBLESTONE;
	public static final Block OBSIDIAN;
	public static final Block aa;
	public static final BlockFire ab;
	public static final Block ac;
	public static final Block ad;
	public static final BlockChest ae;
	public static final BlockRedstoneWire af;
	public static final Block ag;
	public static final Block ah;
	public static final Block ai;
	public static final Block aj;
	public static final Block ak;
	public static final Block al;
	public static final Block am;
	public static final Block an;
	public static final Block ao;
	public static final Block ap;
	public static final Block aq;
	public static final Block ar;
	public static final Block as;
	public static final Block at;
	public static final Block au;
	public static final Block av;
	public static final Block aw;
	public static final Block ax;
	public static final Block ay;
	public static final Block az;
	public static final Block aA;
	public static final Block aB;
	public static final Block aC;
	public static final Block aD;
	public static final Block aE;
	public static final Block aF;
	public static final Block aG;
	public static final Block aH;
	public static final Block aI;
	public static final Block aJ;
	public static final BlockCactus aK;
	public static final Block aL;
	public static final BlockReed aM;
	public static final Block aN;
	public static final Block aO;
	public static final Block aP;
	public static final Block aQ;
	public static final Block aR;
	public static final Block aS;
	public static final Block aT;
	public static final Block aU;
	public static final Block aV;
	public static final Block aW;
	public static final Block aX;
	public static final BlockPortal aY;
	public static final Block aZ;
	public static final Block ba;
	public static final BlockRepeater bb;
	public static final BlockRepeater bc;
	public static final Block bd;
	public static final Block be;
	public static final Block bf;
	public static final Block bg;
	public static final Block bh;
	public static final Block bi;
	public static final Block bj;
	public static final Block bk;
	public static final Block bl;
	public static final Block bm;
	public static final Block bn;
	public static final Block bo;
	public static final Block bp;
	public static final Block bq;
	public static final Block br;
	public static final Block bs;
	public static final Block bt;
	public static final Block bu;
	public static final Block bv;
	public static final BlockMycel bw;
	public static final Block bx;
	public static final Block by;
	public static final Block bz;
	public static final Block bA;
	public static final Block bB;
	public static final Block bC;
	public static final Block bD;
	public static final BlockCauldron bE;
	public static final Block bF;
	public static final Block bG;
	public static final Block bH;
	public static final Block bI;
	public static final Block bJ;
	public static final Block bK;
	public static final BlockStepAbstract bL;
	public static final BlockStepAbstract bM;
	public static final Block bN;
	public static final Block bO;
	public static final Block bP;
	public static final Block bQ;
	public static final BlockTripwireHook bR;
	public static final Block bS;
	public static final Block bT;
	public static final Block bU;
	public static final Block bV;
	public static final Block bW;
	public static final Block bX;
	public static final BlockBeacon bY;
	public static final Block bZ;
	public static final Block ca;
	public static final Block cb;
	public static final Block cc;
	public static final Block cd;
	public static final BlockSkull ce;
	public static final Block cf;
	public static final Block cg;
	public static final Block ch;
	public static final Block ci;
	public static final BlockRedstoneComparator cj;
	public static final BlockRedstoneComparator ck;
	public static final BlockDaylightDetector cl;
	public static final BlockDaylightDetector cm;
	public static final Block cn;
	public static final Block co;
	public static final BlockHopper cp;
	public static final Block cq;
	public static final Block cr;
	public static final Block cs;
	public static final Block ct;
	public static final Block cu;
	public static final Block cv;
	public static final Block cw;
	public static final Block cx;
	public static final Block cy;
	public static final Block cz;
	public static final Block cA;
	public static final Block cB;
	public static final Block cC;
	public static final Block cD;
	public static final Block cE;
	public static final BlockTallPlant cF;
	public static final BlockStainedGlass cG;
	public static final BlockStainedGlassPane cH;
	public static final Block cI;
	public static final Block cJ;
	public static final Block cK;
	public static final Block cL;
	public static final Block cM;
	public static final Block cN;
	public static final BlockStepAbstract cO;
	public static final BlockStepAbstract cP;

	private static Block getBlock(String name) {
		return (Block) Block.BLOCKREGISTRY.getByName(new RegistryObjectName(name));
	}

	static {
		if (!od.a()) {
			throw new RuntimeException("Accessed Blocks before Bootstrap!");
		} else {
			AIR = getBlock("air");
			STONE = getBlock("stone");
			GRASS = (BlockGrass) getBlock("grass");
			DIRT = getBlock("dirt");
			COBBLESTONE = getBlock("cobblestone");
			PLANKS = getBlock("planks");
			SAPLING = getBlock("sapling");
			BEDROCK = getBlock("bedrock");
			FLOWING_WATER = (BlockFlowing) getBlock("flowing_water");
			WATER = (BlockStationary) getBlock("water");
			FLOWING_LAVA = (BlockFlowing) getBlock("flowing_lava");
			LAVA = (BlockStationary) getBlock("lava");
			SAND = (BlockSand) getBlock("sand");
			GRAVEL = getBlock("gravel");
			GOLD_ORE = getBlock("gold_ore");
			IRON_ORE = getBlock("iron_ore");
			COAL_ORE = getBlock("coal_ore");
			LOG = getBlock("log");
			LOG2 = getBlock("log2");
			LEAVES = (BlockLeaves) getBlock("leaves");
			LEAVES2 = (BlockLeaves) getBlock("leaves2");
			SPONGE = getBlock("sponge");
			GLASS = getBlock("glass");
			LAPIS_ORE = getBlock("lapis_ore");
			LAPIS_BLOCK = getBlock("lapis_block");
			DISPENSER = getBlock("dispenser");
			SANDSTONE = getBlock("sandstone");
			NOTEBLOCK = getBlock("noteblock");
			BED = getBlock("bed");
			GOLDEN_RAIL = getBlock("golden_rail");
			DETECTOR_RAIL = getBlock("detector_rail");
			STICKY_PISTON = (BlockPiston) getBlock("sticky_piston");
			WEB = getBlock("web");
			TALLGRASS = (BlockLongGrass) getBlock("tallgrass");
			DEADBUSH = (BlockDeadBush) getBlock("deadbush");
			PISTON = (BlockPiston) getBlock("piston");
			PISTON_HEAD = (BlockPistonExtension) getBlock("piston_head");
			WOOL = getBlock("wool");
			PISTON_EXTENSION = (BlockPistonMoving) getBlock("piston_extension");
			YELLOW_FLOWER = (avy) getBlock("yellow_flower");
			RED_FLOWER = (avy) getBlock("red_flower");
			BRWON_MUSHROOM = (auc) getBlock("brown_mushroom");
			RED_MUSHROOM = (auc) getBlock("red_mushroom");
			GOLD_BLOCK = getBlock("gold_block");
			IRON_BLOCK = getBlock("iron_block");
			DOUBLE_STONE_SLAB = (BlockStepAbstract) getBlock("double_stone_slab");
			STONE_SLAB = (BlockStepAbstract) getBlock("stone_slab");
			BRICK_BLOCK = getBlock("brick_block");
			TNT = getBlock("tnt");
			BOOKSHELF = getBlock("bookshelf");
			MOSSY_COBBLESTONE = getBlock("mossy_cobblestone");
			OBSIDIAN = getBlock("obsidian");
			aa = getBlock("torch");
			ab = (BlockFire) getBlock("fire");
			ac = getBlock("mob_spawner");
			ad = getBlock("oak_stairs");
			ae = (BlockChest) getBlock("chest");
			af = (BlockRedstoneWire) getBlock("redstone_wire");
			ag = getBlock("diamond_ore");
			ah = getBlock("diamond_block");
			ai = getBlock("crafting_table");
			aj = getBlock("wheat");
			ak = getBlock("farmland");
			al = getBlock("furnace");
			am = getBlock("lit_furnace");
			an = getBlock("standing_sign");
			ao = getBlock("wooden_door");
			ap = getBlock("spruce_door");
			aq = getBlock("birch_door");
			ar = getBlock("jungle_door");
			as = getBlock("acacia_door");
			at = getBlock("dark_oak_door");
			au = getBlock("ladder");
			av = getBlock("rail");
			aw = getBlock("stone_stairs");
			ax = getBlock("wall_sign");
			ay = getBlock("lever");
			az = getBlock("stone_pressure_plate");
			aA = getBlock("iron_door");
			aB = getBlock("wooden_pressure_plate");
			aC = getBlock("redstone_ore");
			aD = getBlock("lit_redstone_ore");
			aE = getBlock("unlit_redstone_torch");
			aF = getBlock("redstone_torch");
			aG = getBlock("stone_button");
			aH = getBlock("snow_layer");
			aI = getBlock("ice");
			aJ = getBlock("snow");
			aK = (BlockCactus) getBlock("cactus");
			aL = getBlock("clay");
			aM = (BlockReed) getBlock("reeds");
			aN = getBlock("jukebox");
			aO = getBlock("fence");
			aP = getBlock("spruce_fence");
			aQ = getBlock("birch_fence");
			aR = getBlock("jungle_fence");
			aS = getBlock("dark_oak_fence");
			aT = getBlock("acacia_fence");
			aU = getBlock("pumpkin");
			aV = getBlock("netherrack");
			aW = getBlock("soul_sand");
			aX = getBlock("glowstone");
			aY = (BlockPortal) getBlock("portal");
			aZ = getBlock("lit_pumpkin");
			ba = getBlock("cake");
			bb = (BlockRepeater) getBlock("unpowered_repeater");
			bc = (BlockRepeater) getBlock("powered_repeater");
			bd = getBlock("trapdoor");
			be = getBlock("monster_egg");
			bf = getBlock("stonebrick");
			bg = getBlock("brown_mushroom_block");
			bh = getBlock("red_mushroom_block");
			bi = getBlock("iron_bars");
			bj = getBlock("glass_pane");
			bk = getBlock("melon_block");
			bl = getBlock("pumpkin_stem");
			bm = getBlock("melon_stem");
			bn = getBlock("vine");
			bo = getBlock("fence_gate");
			bp = getBlock("spruce_fence_gate");
			bq = getBlock("birch_fence_gate");
			br = getBlock("jungle_fence_gate");
			bs = getBlock("dark_oak_fence_gate");
			bt = getBlock("acacia_fence_gate");
			bu = getBlock("brick_stairs");
			bv = getBlock("stone_brick_stairs");
			bw = (BlockMycel) getBlock("mycelium");
			bx = getBlock("waterlily");
			by = getBlock("nether_brick");
			bz = getBlock("nether_brick_fence");
			bA = getBlock("nether_brick_stairs");
			bB = getBlock("nether_wart");
			bC = getBlock("enchanting_table");
			bD = getBlock("brewing_stand");
			bE = (BlockCauldron) getBlock("cauldron");
			bF = getBlock("end_portal");
			bG = getBlock("end_portal_frame");
			bH = getBlock("end_stone");
			bI = getBlock("dragon_egg");
			bJ = getBlock("redstone_lamp");
			bK = getBlock("lit_redstone_lamp");
			bL = (BlockStepAbstract) getBlock("double_wooden_slab");
			bM = (BlockStepAbstract) getBlock("wooden_slab");
			bN = getBlock("cocoa");
			bO = getBlock("sandstone_stairs");
			bP = getBlock("emerald_ore");
			bQ = getBlock("ender_chest");
			bR = (BlockTripwireHook) getBlock("tripwire_hook");
			bS = getBlock("tripwire");
			bT = getBlock("emerald_block");
			bU = getBlock("spruce_stairs");
			bV = getBlock("birch_stairs");
			bW = getBlock("jungle_stairs");
			bX = getBlock("command_block");
			bY = (BlockBeacon) getBlock("beacon");
			bZ = getBlock("cobblestone_wall");
			ca = getBlock("flower_pot");
			cb = getBlock("carrots");
			cc = getBlock("potatoes");
			cd = getBlock("wooden_button");
			ce = (BlockSkull) getBlock("skull");
			cf = getBlock("anvil");
			cg = getBlock("trapped_chest");
			ch = getBlock("light_weighted_pressure_plate");
			ci = getBlock("heavy_weighted_pressure_plate");
			cj = (BlockRedstoneComparator) getBlock("unpowered_comparator");
			ck = (BlockRedstoneComparator) getBlock("powered_comparator");
			cl = (BlockDaylightDetector) getBlock("daylight_detector");
			cm = (BlockDaylightDetector) getBlock("daylight_detector_inverted");
			cn = getBlock("redstone_block");
			co = getBlock("quartz_ore");
			cp = (BlockHopper) getBlock("hopper");
			cq = getBlock("quartz_block");
			cr = getBlock("quartz_stairs");
			cs = getBlock("activator_rail");
			ct = getBlock("dropper");
			cu = getBlock("stained_hardened_clay");
			cv = getBlock("barrier");
			cw = getBlock("iron_trapdoor");
			cx = getBlock("hay_block");
			cy = getBlock("carpet");
			cz = getBlock("hardened_clay");
			cA = getBlock("coal_block");
			cB = getBlock("packed_ice");
			cC = getBlock("acacia_stairs");
			cD = getBlock("dark_oak_stairs");
			cE = getBlock("slime");
			cF = (BlockTallPlant) getBlock("double_plant");
			cG = (BlockStainedGlass) getBlock("stained_glass");
			cH = (BlockStainedGlassPane) getBlock("stained_glass_pane");
			cI = getBlock("prismarine");
			cJ = getBlock("sea_lantern");
			cK = getBlock("standing_banner");
			cL = getBlock("wall_banner");
			cM = getBlock("red_sandstone");
			cN = getBlock("red_sandstone_stairs");
			cO = (BlockStepAbstract) getBlock("double_stone_slab2");
			cP = (BlockStepAbstract) getBlock("stone_slab2");
		}
	}
}
