package net.minecraft;

public class ChunkProviderGenerateProperties {

	public final float coordinateScale;
	public final float heightScale;
	public final float upperLimitScale;
	public final float lowerLimitScale;
	public final float depthNoiseScaleX;
	public final float depthNoiseScaleZ;
	public final float depthNoiseScaleExponent;
	public final float mainNoiseScaleX;
	public final float mainNoiseScaleY;
	public final float mainNoiseScaleZ;
	public final float baseSize;
	public final float stretchY;
	public final float biomeDepthWeight;
	public final float biomeDepthOffset;
	public final float biomeScaleWeight;
	public final float biomeScaleOffset;
	public final int seaLevel;
	public final boolean useCaves;
	public final boolean useDungeons;
	public final int dungeonChance;
	public final boolean useStrongholds;
	public final boolean useVillages;
	public final boolean useMineShafts;
	public final boolean useTemples;
	public final boolean useMonuments;
	public final boolean useRavines;
	public final boolean useWaterLakes;
	public final int waterLakeChance;
	public final boolean useLavaLakes;
	public final int lavaLakeChance;
	public final boolean useLavaOceans;
	public final int fixedBiome;
	public final int biomeSize;
	public final int riverSize;
	public final int dirtSize;
	public final int dirtCount;
	public final int dirtMinHeight;
	public final int dirtMaxHeight;
	public final int gravelSize;
	public final int gravelCount;
	public final int gravelMinHeight;
	public final int gravelMaxHeight;
	public final int graniteSize;
	public final int graniteCount;
	public final int graniteMinHeight;
	public final int graniteMaxHeight;
	public final int dioriteSize;
	public final int dioriteCount;
	public final int dioriteMinHeight;
	public final int dioriteMaxHeight;
	public final int andesiteSize;
	public final int andesiteCount;
	public final int andesiteMinHeight;
	public final int andesiteMaxHeight;
	public final int coalSize;
	public final int coalCount;
	public final int coalMinHeight;
	public final int coalMaxHeight;
	public final int ironSize;
	public final int ironCount;
	public final int ironMinHeight;
	public final int ironMaxHeight;
	public final int goldSize;
	public final int goldCount;
	public final int goldMinHeight;
	public final int goldMaxHeight;
	public final int redstoneSize;
	public final int redstoneCount;
	public final int redstoneMinHeight;
	public final int redstoneMaxHeight;
	public final int diamondSize;
	public final int diamondCount;
	public final int diamondMinHeight;
	public final int diamondMaxHeight;
	public final int lapisSize;
	public final int lapisCount;
	public final int lapisCenterHeight;
	public final int lapisSpread;

	public ChunkProviderGenerateProperties(ChunkProviderGeneratePropertiesHolder properties) {
		this.coordinateScale = properties.coordinateScale;
		this.heightScale = properties.heightScale;
		this.upperLimitScale = properties.upperLimitScale;
		this.lowerLimitScale = properties.lowerLimitScale;
		this.depthNoiseScaleX = properties.depthNoiseScaleX;
		this.depthNoiseScaleZ = properties.depthNoiseScaleZ;
		this.depthNoiseScaleExponent = properties.depthNoiseScaleExponent;
		this.mainNoiseScaleX = properties.mainNoiseScaleX;
		this.mainNoiseScaleY = properties.mainNoiseScaleY;
		this.mainNoiseScaleZ = properties.mainNoiseScaleZ;
		this.baseSize = properties.baseSize;
		this.stretchY = properties.stretchY;
		this.biomeDepthWeight = properties.biomeDepthWeight;
		this.biomeDepthOffset = properties.biomeDepthOffset;
		this.biomeScaleWeight = properties.biomeScaleWeight;
		this.biomeScaleOffset = properties.biomeScaleOffset;
		this.seaLevel = properties.seaLevel;
		this.useCaves = properties.useCaves;
		this.useDungeons = properties.useDungeons;
		this.dungeonChance = properties.dungeonChance;
		this.useStrongholds = properties.useStrongholds;
		this.useVillages = properties.useVillages;
		this.useMineShafts = properties.useMineShafts;
		this.useTemples = properties.useTemples;
		this.useMonuments = properties.useMonuments;
		this.useRavines = properties.useRavines;
		this.useWaterLakes = properties.useWaterLakes;
		this.waterLakeChance = properties.waterLakeChance;
		this.useLavaLakes = properties.useLavaLakes;
		this.lavaLakeChance = properties.lavaLakeChance;
		this.useLavaOceans = properties.useLavaOceans;
		this.fixedBiome = properties.fixedBiome;
		this.biomeSize = properties.biomeSize;
		this.riverSize = properties.riverSize;
		this.dirtSize = properties.dirtSize;
		this.dirtCount = properties.dirtCount;
		this.dirtMinHeight = properties.dirtMinHeight;
		this.dirtMaxHeight = properties.dirtMaxHeight;
		this.gravelSize = properties.gravelSize;
		this.gravelCount = properties.gravelCount;
		this.gravelMinHeight = properties.gravelMinHeight;
		this.gravelMaxHeight = properties.gravelMaxHeight;
		this.graniteSize = properties.graniteSize;
		this.graniteCount = properties.graniteCount;
		this.graniteMinHeight = properties.graniteMinHeight;
		this.graniteMaxHeight = properties.graniteMaxHeight;
		this.dioriteSize = properties.dioriteSize;
		this.dioriteCount = properties.dioriteCount;
		this.dioriteMinHeight = properties.dioriteMinHeight;
		this.dioriteMaxHeight = properties.dioriteMaxHeight;
		this.andesiteSize = properties.andesiteSize;
		this.andesiteCount = properties.andesiteCount;
		this.andesiteMinHeight = properties.andesiteMinHeight;
		this.andesiteMaxHeight = properties.andesiteMaxHeight;
		this.coalSize = properties.coalSize;
		this.coalCount = properties.coalCount;
		this.coalMinHeight = properties.coalMinHeight;
		this.coalMaxHeight = properties.coalMaxHeight;
		this.ironSize = properties.ironSize;
		this.ironCount = properties.ironCount;
		this.ironMinHeight = properties.ironMinHeight;
		this.ironMaxHeight = properties.ironMaxHeight;
		this.goldSize = properties.goldSize;
		this.goldCount = properties.goldCount;
		this.goldMinHeight = properties.goldMinHeight;
		this.goldMaxHeight = properties.goldMaxHeight;
		this.redstoneSize = properties.redstoneSize;
		this.redstoneCount = properties.redstoneCount;
		this.redstoneMinHeight = properties.redstoneMinHeight;
		this.redstoneMaxHeight = properties.redstoneMaxHeight;
		this.diamondSize = properties.diamondSize;
		this.diamondCount = properties.diamondCount;
		this.diamondMinHeight = properties.diamondMinHeight;
		this.diamondMaxHeight = properties.diamondMaxHeight;
		this.lapisSize = properties.lapisSize;
		this.lapisCount = properties.lapisCount;
		this.lapisCenterHeight = properties.lapisCenterHeight;
		this.lapisSpread = properties.lapisSpread;
	}

}
